apiVersion: v1
kind: Pod
metadata:
  name: firefox-pod
  namespace: default

spec:
  containers:
  - image: linuxserver/firefox
    name: firefox-cont
    ports:
      - containerPort: 3000
