apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: testserver
  ports:
  - port: 9090
    targetPort: 80
